In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn import datasets

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Convert to DataFrame
df = pd.DataFrame(X, columns=iris.feature_names)
df['target'] = y

# Splitting dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

# Train KNN classifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

# Predictions
y_pred = knn.predict(X_test)

# Evaluate model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Print correct and incorrect predictions
print("\nCorrect Predictions:")
for i in range(len(y_test)):
    if y_test[i] == y_pred[i]:
        print(f"Index {i}: True Label = {y_test[i]}, Predicted = {y_pred[i]}")

print("\nIncorrect Predictions:")
for i in range(len(y_test)):
    if y_test[i] != y_pred[i]:
        print(f"Index {i}: True Label = {y_test[i]}, Predicted = {y_pred[i]}")

Accuracy: 0.98
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        23
           1       0.95      1.00      0.97        19
           2       1.00      0.94      0.97        18

    accuracy                           0.98        60
   macro avg       0.98      0.98      0.98        60
weighted avg       0.98      0.98      0.98        60

Confusion Matrix:
[[23  0  0]
 [ 0 19  0]
 [ 0  1 17]]

Correct Predictions:
Index 0: True Label = 1, Predicted = 1
Index 1: True Label = 0, Predicted = 0
Index 2: True Label = 2, Predicted = 2
Index 3: True Label = 1, Predicted = 1
Index 4: True Label = 1, Predicted = 1
Index 5: True Label = 0, Predicted = 0
Index 6: True Label = 1, Predicted = 1
Index 7: True Label = 2, Predicted = 2
Index 8: True Label = 1, Predicted = 1
Index 9: True Label = 1, Predicted = 1
Index 10: True Label = 2, Predicted = 2
Index 11: True Label = 0, Predicted = 0
Index 12: True Label = 0, Predicte